language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="Rubber Band Cannon Arduino Code"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
# Install ServoTimer2 from git
   - mkdir -p ~/Arduino/libraries
   - wget https://github.com/nabontra/ServoTimer2/archive/master.zip && unzip master.zip -d ~/Arduino/libraries/

install:
# https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
   - arduino --install-library "AltSoftSerial","MemoryUsage","Stepper"
   - cd $TRAVIS_BUILD_DIR/arduino/ESP8266_webserver/ && source generate_headers_from_html.bash

script:
   - cd $TRAVIS_BUILD_DIR/arduino/ESP8266_webserver/ && build_main_platforms

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/arduino/ESP8266_webserver/ && source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - cd $TRAVIS_BUILD_DIR/arduino/ESP8266_webserver/ && source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)